// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_GlassPlayer_H
#define WINRT_GlassPlayer_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.240405.15"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.240405.15"
#include "winrt/impl/Microsoft.UI.Xaml.2.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.2.h"
#include "winrt/impl/GlassPlayer.2.h"
namespace winrt::impl
{
    template <typename D>
    struct produce<D, winrt::GlassPlayer::IApp> : produce_base<D, winrt::GlassPlayer::IApp>
    {
    };
    template <typename D>
    struct produce<D, winrt::GlassPlayer::IMainWindow> : produce_base<D, winrt::GlassPlayer::IMainWindow>
    {
    };
    template <typename D>
    struct produce<D, winrt::GlassPlayer::IRcloneBrowser> : produce_base<D, winrt::GlassPlayer::IRcloneBrowser>
    {
    };
    template <typename D>
    struct produce<D, winrt::GlassPlayer::ISettingsWindow> : produce_base<D, winrt::GlassPlayer::ISettingsWindow>
    {
    };
    template <typename D>
    struct produce<D, winrt::GlassPlayer::IWelcomeWindow> : produce_base<D, winrt::GlassPlayer::IWelcomeWindow>
    {
    };
}
WINRT_EXPORT namespace winrt::GlassPlayer
{
    inline App::App() :
        App(impl::call_factory_cast<App(*)(winrt::Windows::Foundation::IActivationFactory const&), App>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<App>(); }))
    {
    }
    inline MainWindow::MainWindow() :
        MainWindow(impl::call_factory_cast<MainWindow(*)(winrt::Windows::Foundation::IActivationFactory const&), MainWindow>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<MainWindow>(); }))
    {
    }
    inline RcloneBrowser::RcloneBrowser() :
        RcloneBrowser(impl::call_factory_cast<RcloneBrowser(*)(winrt::Windows::Foundation::IActivationFactory const&), RcloneBrowser>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<RcloneBrowser>(); }))
    {
    }
    inline SettingsWindow::SettingsWindow() :
        SettingsWindow(impl::call_factory_cast<SettingsWindow(*)(winrt::Windows::Foundation::IActivationFactory const&), SettingsWindow>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<SettingsWindow>(); }))
    {
    }
    inline WelcomeWindow::WelcomeWindow() :
        WelcomeWindow(impl::call_factory_cast<WelcomeWindow(*)(winrt::Windows::Foundation::IActivationFactory const&), WelcomeWindow>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<WelcomeWindow>(); }))
    {
    }
    inline XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(impl::call_factory_cast<XamlMetaDataProvider(*)(winrt::Windows::Foundation::IActivationFactory const&), XamlMetaDataProvider>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<XamlMetaDataProvider>(); }))
    {
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::GlassPlayer::IApp> : winrt::impl::hash_base {};
    template<> struct hash<winrt::GlassPlayer::IMainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::GlassPlayer::IRcloneBrowser> : winrt::impl::hash_base {};
    template<> struct hash<winrt::GlassPlayer::ISettingsWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::GlassPlayer::IWelcomeWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::GlassPlayer::App> : winrt::impl::hash_base {};
    template<> struct hash<winrt::GlassPlayer::MainWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::GlassPlayer::RcloneBrowser> : winrt::impl::hash_base {};
    template<> struct hash<winrt::GlassPlayer::SettingsWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::GlassPlayer::WelcomeWindow> : winrt::impl::hash_base {};
    template<> struct hash<winrt::GlassPlayer::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
