// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_GlassPlayer_1_H
#define WINRT_GlassPlayer_1_H
#include "winrt/impl/GlassPlayer.0.h"
WINRT_EXPORT namespace winrt::GlassPlayer
{
    struct WINRT_IMPL_EMPTY_BASES IApp :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IApp>
    {
        IApp(std::nullptr_t = nullptr) noexcept {}
        IApp(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IMainWindow :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMainWindow>
    {
        IMainWindow(std::nullptr_t = nullptr) noexcept {}
        IMainWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IRcloneBrowser :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRcloneBrowser>
    {
        IRcloneBrowser(std::nullptr_t = nullptr) noexcept {}
        IRcloneBrowser(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ISettingsWindow :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISettingsWindow>
    {
        ISettingsWindow(std::nullptr_t = nullptr) noexcept {}
        ISettingsWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES IWelcomeWindow :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IWelcomeWindow>
    {
        IWelcomeWindow(std::nullptr_t = nullptr) noexcept {}
        IWelcomeWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
