// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_GlassPlayer_0_H
#define WINRT_GlassPlayer_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::GlassPlayer
{
    struct IApp;
    struct IMainWindow;
    struct IRcloneBrowser;
    struct ISettingsWindow;
    struct IWelcomeWindow;
    struct App;
    struct MainWindow;
    struct RcloneBrowser;
    struct SettingsWindow;
    struct WelcomeWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::GlassPlayer::IApp>{ using type = interface_category; };
    template <> struct category<winrt::GlassPlayer::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::GlassPlayer::IRcloneBrowser>{ using type = interface_category; };
    template <> struct category<winrt::GlassPlayer::ISettingsWindow>{ using type = interface_category; };
    template <> struct category<winrt::GlassPlayer::IWelcomeWindow>{ using type = interface_category; };
    template <> struct category<winrt::GlassPlayer::App>{ using type = class_category; };
    template <> struct category<winrt::GlassPlayer::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::GlassPlayer::RcloneBrowser>{ using type = class_category; };
    template <> struct category<winrt::GlassPlayer::SettingsWindow>{ using type = class_category; };
    template <> struct category<winrt::GlassPlayer::WelcomeWindow>{ using type = class_category; };
    template <> struct category<winrt::GlassPlayer::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::GlassPlayer::App> = L"GlassPlayer.App";
    template <> inline constexpr auto& name_v<winrt::GlassPlayer::MainWindow> = L"GlassPlayer.MainWindow";
    template <> inline constexpr auto& name_v<winrt::GlassPlayer::RcloneBrowser> = L"GlassPlayer.RcloneBrowser";
    template <> inline constexpr auto& name_v<winrt::GlassPlayer::SettingsWindow> = L"GlassPlayer.SettingsWindow";
    template <> inline constexpr auto& name_v<winrt::GlassPlayer::WelcomeWindow> = L"GlassPlayer.WelcomeWindow";
    template <> inline constexpr auto& name_v<winrt::GlassPlayer::XamlMetaDataProvider> = L"GlassPlayer.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::GlassPlayer::IApp> = L"GlassPlayer.IApp";
    template <> inline constexpr auto& name_v<winrt::GlassPlayer::IMainWindow> = L"GlassPlayer.IMainWindow";
    template <> inline constexpr auto& name_v<winrt::GlassPlayer::IRcloneBrowser> = L"GlassPlayer.IRcloneBrowser";
    template <> inline constexpr auto& name_v<winrt::GlassPlayer::ISettingsWindow> = L"GlassPlayer.ISettingsWindow";
    template <> inline constexpr auto& name_v<winrt::GlassPlayer::IWelcomeWindow> = L"GlassPlayer.IWelcomeWindow";
    template <> inline constexpr guid guid_v<winrt::GlassPlayer::IApp>{ 0xCB1F85B7,0x3BC3,0x5245,{ 0x82,0x09,0x9F,0x81,0x3D,0x1D,0x71,0xC6 } }; // CB1F85B7-3BC3-5245-8209-9F813D1D71C6
    template <> inline constexpr guid guid_v<winrt::GlassPlayer::IMainWindow>{ 0xF940775C,0x2D57,0x5838,{ 0xB0,0x05,0x07,0x87,0xD9,0x22,0x31,0xC6 } }; // F940775C-2D57-5838-B005-0787D92231C6
    template <> inline constexpr guid guid_v<winrt::GlassPlayer::IRcloneBrowser>{ 0xD2B2EABB,0xD50E,0x5529,{ 0xAC,0x9B,0x2B,0xBB,0x2A,0xBD,0x7B,0x09 } }; // D2B2EABB-D50E-5529-AC9B-2BBB2ABD7B09
    template <> inline constexpr guid guid_v<winrt::GlassPlayer::ISettingsWindow>{ 0x01F4282D,0xFD4A,0x5C8F,{ 0xA1,0xFB,0x6A,0xCA,0x2B,0x92,0xFF,0x98 } }; // 01F4282D-FD4A-5C8F-A1FB-6ACA2B92FF98
    template <> inline constexpr guid guid_v<winrt::GlassPlayer::IWelcomeWindow>{ 0xF2C76829,0xC0BE,0x50C6,{ 0x9A,0x07,0x50,0x7E,0x5B,0x45,0x9A,0xCD } }; // F2C76829-C0BE-50C6-9A07-507E5B459ACD
    template <> struct default_interface<winrt::GlassPlayer::App>{ using type = winrt::GlassPlayer::IApp; };
    template <> struct default_interface<winrt::GlassPlayer::MainWindow>{ using type = winrt::GlassPlayer::IMainWindow; };
    template <> struct default_interface<winrt::GlassPlayer::RcloneBrowser>{ using type = winrt::GlassPlayer::IRcloneBrowser; };
    template <> struct default_interface<winrt::GlassPlayer::SettingsWindow>{ using type = winrt::GlassPlayer::ISettingsWindow; };
    template <> struct default_interface<winrt::GlassPlayer::WelcomeWindow>{ using type = winrt::GlassPlayer::IWelcomeWindow; };
    template <> struct default_interface<winrt::GlassPlayer::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::GlassPlayer::IApp>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::GlassPlayer::IMainWindow>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::GlassPlayer::IRcloneBrowser>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::GlassPlayer::ISettingsWindow>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <> struct abi<winrt::GlassPlayer::IWelcomeWindow>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_GlassPlayer_IApp
    {
    };
    template <> struct consume<winrt::GlassPlayer::IApp>
    {
        template <typename D> using type = consume_GlassPlayer_IApp<D>;
    };
    template <typename D>
    struct consume_GlassPlayer_IMainWindow
    {
    };
    template <> struct consume<winrt::GlassPlayer::IMainWindow>
    {
        template <typename D> using type = consume_GlassPlayer_IMainWindow<D>;
    };
    template <typename D>
    struct consume_GlassPlayer_IRcloneBrowser
    {
    };
    template <> struct consume<winrt::GlassPlayer::IRcloneBrowser>
    {
        template <typename D> using type = consume_GlassPlayer_IRcloneBrowser<D>;
    };
    template <typename D>
    struct consume_GlassPlayer_ISettingsWindow
    {
    };
    template <> struct consume<winrt::GlassPlayer::ISettingsWindow>
    {
        template <typename D> using type = consume_GlassPlayer_ISettingsWindow<D>;
    };
    template <typename D>
    struct consume_GlassPlayer_IWelcomeWindow
    {
    };
    template <> struct consume<winrt::GlassPlayer::IWelcomeWindow>
    {
        template <typename D> using type = consume_GlassPlayer_IWelcomeWindow<D>;
    };
}
#endif
