// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_GlassPlayer_2_H
#define WINRT_GlassPlayer_2_H
#include "winrt/impl/Microsoft.UI.Xaml.1.h"
#include "winrt/impl/Microsoft.UI.Xaml.Markup.1.h"
#include "winrt/impl/GlassPlayer.1.h"
WINRT_EXPORT namespace winrt::GlassPlayer
{
    struct WINRT_IMPL_EMPTY_BASES App : winrt::GlassPlayer::IApp,
        impl::base<App, winrt::Microsoft::UI::Xaml::Application>,
        impl::require<App, winrt::Microsoft::UI::Xaml::IApplication, winrt::Microsoft::UI::Xaml::IApplication2, winrt::Microsoft::UI::Xaml::IApplication3>
    {
        App(std::nullptr_t) noexcept {}
        App(void* ptr, take_ownership_from_abi_t) noexcept : winrt::GlassPlayer::IApp(ptr, take_ownership_from_abi) {}
        App();
    };
    struct WINRT_IMPL_EMPTY_BASES MainWindow : winrt::GlassPlayer::IMainWindow,
        impl::base<MainWindow, winrt::Microsoft::UI::Xaml::Window>,
        impl::require<MainWindow, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>
    {
        MainWindow(std::nullptr_t) noexcept {}
        MainWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::GlassPlayer::IMainWindow(ptr, take_ownership_from_abi) {}
        MainWindow();
    };
    struct WINRT_IMPL_EMPTY_BASES RcloneBrowser : winrt::GlassPlayer::IRcloneBrowser,
        impl::base<RcloneBrowser, winrt::Microsoft::UI::Xaml::Window>,
        impl::require<RcloneBrowser, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>
    {
        RcloneBrowser(std::nullptr_t) noexcept {}
        RcloneBrowser(void* ptr, take_ownership_from_abi_t) noexcept : winrt::GlassPlayer::IRcloneBrowser(ptr, take_ownership_from_abi) {}
        RcloneBrowser();
    };
    struct WINRT_IMPL_EMPTY_BASES SettingsWindow : winrt::GlassPlayer::ISettingsWindow,
        impl::base<SettingsWindow, winrt::Microsoft::UI::Xaml::Window>,
        impl::require<SettingsWindow, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>
    {
        SettingsWindow(std::nullptr_t) noexcept {}
        SettingsWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::GlassPlayer::ISettingsWindow(ptr, take_ownership_from_abi) {}
        SettingsWindow();
    };
    struct WINRT_IMPL_EMPTY_BASES WelcomeWindow : winrt::GlassPlayer::IWelcomeWindow,
        impl::base<WelcomeWindow, winrt::Microsoft::UI::Xaml::Window>,
        impl::require<WelcomeWindow, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>
    {
        WelcomeWindow(std::nullptr_t) noexcept {}
        WelcomeWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::GlassPlayer::IWelcomeWindow(ptr, take_ownership_from_abi) {}
        WelcomeWindow();
    };
    struct WINRT_IMPL_EMPTY_BASES XamlMetaDataProvider : winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider
    {
        XamlMetaDataProvider(std::nullptr_t) noexcept {}
        XamlMetaDataProvider(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider(ptr, take_ownership_from_abi) {}
        XamlMetaDataProvider();
    };
}
#endif
