// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_Microsoft_Graphics_Canvas_Printing_1_H
#define WINRT_Microsoft_Graphics_Canvas_Printing_1_H
#include "winrt/impl/Microsoft.Graphics.Canvas.0.h"
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Windows.Graphics.Printing.0.h"
#include "winrt/impl/Microsoft.Graphics.Canvas.Printing.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::Printing
{
    struct WINRT_IMPL_EMPTY_BASES ICanvasPreviewEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasPreviewEventArgs>
    {
        ICanvasPreviewEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICanvasPreviewEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasPrintDeferral :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasPrintDeferral>
    {
        ICanvasPrintDeferral(std::nullptr_t = nullptr) noexcept {}
        ICanvasPrintDeferral(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasPrintDocument :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasPrintDocument>,
        impl::require<winrt::Microsoft::Graphics::Canvas::Printing::ICanvasPrintDocument, winrt::Windows::Foundation::IClosable, winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator, winrt::Windows::Graphics::Printing::IPrintDocumentSource>
    {
        ICanvasPrintDocument(std::nullptr_t = nullptr) noexcept {}
        ICanvasPrintDocument(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasPrintDocumentFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasPrintDocumentFactory>
    {
        ICanvasPrintDocumentFactory(std::nullptr_t = nullptr) noexcept {}
        ICanvasPrintDocumentFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasPrintEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasPrintEventArgs>
    {
        ICanvasPrintEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICanvasPrintEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasPrintTaskOptionsChangedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasPrintTaskOptionsChangedEventArgs>
    {
        ICanvasPrintTaskOptionsChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICanvasPrintTaskOptionsChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
