// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_Microsoft_Graphics_Canvas_UI_Xaml_1_H
#define WINRT_Microsoft_Graphics_Canvas_UI_Xaml_1_H
#include "winrt/impl/Microsoft.Graphics.Canvas.0.h"
#include "winrt/impl/Microsoft.Graphics.Canvas.UI.Xaml.0.h"
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::UI::Xaml
{
    struct WINRT_IMPL_EMPTY_BASES ICanvasAnimatedControl :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasAnimatedControl>,
        impl::require<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasAnimatedControl, winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator, winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi>
    {
        ICanvasAnimatedControl(std::nullptr_t = nullptr) noexcept {}
        ICanvasAnimatedControl(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasAnimatedDrawEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasAnimatedDrawEventArgs>
    {
        ICanvasAnimatedDrawEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICanvasAnimatedDrawEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasAnimatedDrawEventArgsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasAnimatedDrawEventArgsFactory>
    {
        ICanvasAnimatedDrawEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        ICanvasAnimatedDrawEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasAnimatedUpdateEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasAnimatedUpdateEventArgs>
    {
        ICanvasAnimatedUpdateEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICanvasAnimatedUpdateEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasAnimatedUpdateEventArgsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasAnimatedUpdateEventArgsFactory>
    {
        ICanvasAnimatedUpdateEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        ICanvasAnimatedUpdateEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasControl :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasControl>,
        impl::require<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl, winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator, winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi>
    {
        ICanvasControl(std::nullptr_t = nullptr) noexcept {}
        ICanvasControl(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasDrawEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasDrawEventArgs>
    {
        ICanvasDrawEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICanvasDrawEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasDrawEventArgsFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasDrawEventArgsFactory>
    {
        ICanvasDrawEventArgsFactory(std::nullptr_t = nullptr) noexcept {}
        ICanvasDrawEventArgsFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasImageSource :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasImageSource>,
        impl::require<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSource, winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator, winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi>
    {
        ICanvasImageSource(std::nullptr_t = nullptr) noexcept {}
        ICanvasImageSource(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasImageSourceFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasImageSourceFactory>
    {
        ICanvasImageSourceFactory(std::nullptr_t = nullptr) noexcept {}
        ICanvasImageSourceFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasRegionsInvalidatedEventArgs :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasRegionsInvalidatedEventArgs>
    {
        ICanvasRegionsInvalidatedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICanvasRegionsInvalidatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasSwapChainPanel :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasSwapChainPanel>
    {
        ICanvasSwapChainPanel(std::nullptr_t = nullptr) noexcept {}
        ICanvasSwapChainPanel(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasVirtualControl :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasVirtualControl>,
        impl::require<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl, winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator, winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi>
    {
        ICanvasVirtualControl(std::nullptr_t = nullptr) noexcept {}
        ICanvasVirtualControl(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasVirtualImageSource :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasVirtualImageSource>,
        impl::require<winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSource, winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator, winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi>
    {
        ICanvasVirtualImageSource(std::nullptr_t = nullptr) noexcept {}
        ICanvasVirtualImageSource(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES ICanvasVirtualImageSourceFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ICanvasVirtualImageSourceFactory>
    {
        ICanvasVirtualImageSourceFactory(std::nullptr_t = nullptr) noexcept {}
        ICanvasVirtualImageSourceFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
