// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_Microsoft_Graphics_Canvas_UI_Xaml_2_H
#define WINRT_Microsoft_Graphics_Canvas_UI_Xaml_2_H
#include "winrt/impl/Microsoft.Graphics.Canvas.1.h"
#include "winrt/impl/Microsoft.Graphics.Canvas.UI.1.h"
#include "winrt/impl/Microsoft.UI.Composition.1.h"
#include "winrt/impl/Microsoft.UI.Xaml.1.h"
#include "winrt/impl/Microsoft.UI.Xaml.Controls.1.h"
#include "winrt/impl/Microsoft.UI.Xaml.Media.1.h"
#include "winrt/impl/Microsoft.UI.Xaml.Media.Imaging.1.h"
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Microsoft.Graphics.Canvas.UI.Xaml.1.h"
WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::UI::Xaml
{
    struct WINRT_IMPL_EMPTY_BASES CanvasAnimatedControl : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasAnimatedControl,
        impl::base<CanvasAnimatedControl, winrt::Microsoft::UI::Xaml::Controls::UserControl, winrt::Microsoft::UI::Xaml::Controls::Control, winrt::Microsoft::UI::Xaml::FrameworkElement, winrt::Microsoft::UI::Xaml::UIElement, winrt::Microsoft::UI::Xaml::DependencyObject>,
        impl::require<CanvasAnimatedControl, winrt::Microsoft::UI::Xaml::Controls::IUserControl, winrt::Microsoft::UI::Xaml::Controls::IControl, winrt::Microsoft::UI::Xaml::IFrameworkElement, winrt::Microsoft::UI::Xaml::IUIElement, winrt::Microsoft::UI::Composition::IAnimationObject, winrt::Microsoft::UI::Composition::IVisualElement, winrt::Microsoft::UI::Composition::IVisualElement2, winrt::Microsoft::UI::Xaml::IDependencyObject>
    {
        CanvasAnimatedControl(std::nullptr_t) noexcept {}
        CanvasAnimatedControl(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasAnimatedControl(ptr, take_ownership_from_abi) {}
        CanvasAnimatedControl();
    };
    struct WINRT_IMPL_EMPTY_BASES CanvasAnimatedDrawEventArgs : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasAnimatedDrawEventArgs
    {
        CanvasAnimatedDrawEventArgs(std::nullptr_t) noexcept {}
        CanvasAnimatedDrawEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasAnimatedDrawEventArgs(ptr, take_ownership_from_abi) {}
        CanvasAnimatedDrawEventArgs(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession const& canvasDrawingSession, winrt::Microsoft::Graphics::Canvas::UI::CanvasTimingInformation const& timingInformation);
    };
    struct WINRT_IMPL_EMPTY_BASES CanvasAnimatedUpdateEventArgs : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasAnimatedUpdateEventArgs
    {
        CanvasAnimatedUpdateEventArgs(std::nullptr_t) noexcept {}
        CanvasAnimatedUpdateEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasAnimatedUpdateEventArgs(ptr, take_ownership_from_abi) {}
        explicit CanvasAnimatedUpdateEventArgs(winrt::Microsoft::Graphics::Canvas::UI::CanvasTimingInformation const& timingInformation);
    };
    struct WINRT_IMPL_EMPTY_BASES CanvasControl : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl,
        impl::base<CanvasControl, winrt::Microsoft::UI::Xaml::Controls::UserControl, winrt::Microsoft::UI::Xaml::Controls::Control, winrt::Microsoft::UI::Xaml::FrameworkElement, winrt::Microsoft::UI::Xaml::UIElement, winrt::Microsoft::UI::Xaml::DependencyObject>,
        impl::require<CanvasControl, winrt::Microsoft::UI::Xaml::Controls::IUserControl, winrt::Microsoft::UI::Xaml::Controls::IControl, winrt::Microsoft::UI::Xaml::IFrameworkElement, winrt::Microsoft::UI::Xaml::IUIElement, winrt::Microsoft::UI::Composition::IAnimationObject, winrt::Microsoft::UI::Composition::IVisualElement, winrt::Microsoft::UI::Composition::IVisualElement2, winrt::Microsoft::UI::Xaml::IDependencyObject>
    {
        CanvasControl(std::nullptr_t) noexcept {}
        CanvasControl(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasControl(ptr, take_ownership_from_abi) {}
        CanvasControl();
    };
    struct WINRT_IMPL_EMPTY_BASES CanvasDrawEventArgs : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgs
    {
        CanvasDrawEventArgs(std::nullptr_t) noexcept {}
        CanvasDrawEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasDrawEventArgs(ptr, take_ownership_from_abi) {}
        explicit CanvasDrawEventArgs(winrt::Microsoft::Graphics::Canvas::CanvasDrawingSession const& canvasDrawingSession);
    };
    struct WINRT_IMPL_EMPTY_BASES CanvasImageSource : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSource,
        impl::base<CanvasImageSource, winrt::Microsoft::UI::Xaml::Media::Imaging::SurfaceImageSource, winrt::Microsoft::UI::Xaml::Media::ImageSource, winrt::Microsoft::UI::Xaml::DependencyObject>,
        impl::require<CanvasImageSource, winrt::Microsoft::UI::Xaml::Media::Imaging::ISurfaceImageSource, winrt::Microsoft::UI::Xaml::Media::IImageSource, winrt::Microsoft::UI::Xaml::IDependencyObject>
    {
        CanvasImageSource(std::nullptr_t) noexcept {}
        CanvasImageSource(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasImageSource(ptr, take_ownership_from_abi) {}
        CanvasImageSource(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi const& resourceCreator, winrt::Windows::Foundation::Size const& size);
        CanvasImageSource(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi const& resourceCreator, float width, float height);
        CanvasImageSource(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator const& resourceCreator, float width, float height, float dpi);
        CanvasImageSource(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator const& resourceCreator, float width, float height, float dpi, winrt::Microsoft::Graphics::Canvas::CanvasAlphaMode const& alphaMode);
    };
    struct WINRT_IMPL_EMPTY_BASES CanvasRegionsInvalidatedEventArgs : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasRegionsInvalidatedEventArgs
    {
        CanvasRegionsInvalidatedEventArgs(std::nullptr_t) noexcept {}
        CanvasRegionsInvalidatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasRegionsInvalidatedEventArgs(ptr, take_ownership_from_abi) {}
    };
    struct WINRT_IMPL_EMPTY_BASES CanvasSwapChainPanel : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasSwapChainPanel,
        impl::base<CanvasSwapChainPanel, winrt::Microsoft::UI::Xaml::Controls::SwapChainPanel, winrt::Microsoft::UI::Xaml::Controls::Grid, winrt::Microsoft::UI::Xaml::Controls::Panel, winrt::Microsoft::UI::Xaml::FrameworkElement, winrt::Microsoft::UI::Xaml::UIElement, winrt::Microsoft::UI::Xaml::DependencyObject>,
        impl::require<CanvasSwapChainPanel, winrt::Microsoft::UI::Xaml::Controls::ISwapChainPanel, winrt::Microsoft::UI::Xaml::Controls::IGrid, winrt::Microsoft::UI::Xaml::Controls::IPanel, winrt::Microsoft::UI::Xaml::IFrameworkElement, winrt::Microsoft::UI::Xaml::IUIElement, winrt::Microsoft::UI::Composition::IAnimationObject, winrt::Microsoft::UI::Composition::IVisualElement, winrt::Microsoft::UI::Composition::IVisualElement2, winrt::Microsoft::UI::Xaml::IDependencyObject>
    {
        CanvasSwapChainPanel(std::nullptr_t) noexcept {}
        CanvasSwapChainPanel(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasSwapChainPanel(ptr, take_ownership_from_abi) {}
        CanvasSwapChainPanel();
    };
    struct WINRT_IMPL_EMPTY_BASES CanvasVirtualControl : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl,
        impl::base<CanvasVirtualControl, winrt::Microsoft::UI::Xaml::Controls::UserControl, winrt::Microsoft::UI::Xaml::Controls::Control, winrt::Microsoft::UI::Xaml::FrameworkElement, winrt::Microsoft::UI::Xaml::UIElement, winrt::Microsoft::UI::Xaml::DependencyObject>,
        impl::require<CanvasVirtualControl, winrt::Microsoft::UI::Xaml::Controls::IUserControl, winrt::Microsoft::UI::Xaml::Controls::IControl, winrt::Microsoft::UI::Xaml::IFrameworkElement, winrt::Microsoft::UI::Xaml::IUIElement, winrt::Microsoft::UI::Composition::IAnimationObject, winrt::Microsoft::UI::Composition::IVisualElement, winrt::Microsoft::UI::Composition::IVisualElement2, winrt::Microsoft::UI::Xaml::IDependencyObject>
    {
        CanvasVirtualControl(std::nullptr_t) noexcept {}
        CanvasVirtualControl(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualControl(ptr, take_ownership_from_abi) {}
        CanvasVirtualControl();
    };
    struct WINRT_IMPL_EMPTY_BASES CanvasVirtualImageSource : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSource
    {
        CanvasVirtualImageSource(std::nullptr_t) noexcept {}
        CanvasVirtualImageSource(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Microsoft::Graphics::Canvas::UI::Xaml::ICanvasVirtualImageSource(ptr, take_ownership_from_abi) {}
        CanvasVirtualImageSource(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi const& resourceCreator, winrt::Windows::Foundation::Size const& size);
        CanvasVirtualImageSource(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreatorWithDpi const& resourceCreator, float width, float height);
        CanvasVirtualImageSource(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator const& resourceCreator, float width, float height, float dpi);
        CanvasVirtualImageSource(winrt::Microsoft::Graphics::Canvas::ICanvasResourceCreator const& resourceCreator, float width, float height, float dpi, winrt::Microsoft::Graphics::Canvas::CanvasAlphaMode const& alphaMode);
    };
}
#endif
