// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#include "winrt/GlassPlayer.h"
#include "winrt/Microsoft.UI.Xaml.h"
namespace winrt::GlassPlayer::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES App_base : implements<D, GlassPlayer::App, composing, winrt::Microsoft::UI::Xaml::IApplicationOverrides, I...>,
        impl::require<D, winrt::Microsoft::UI::Xaml::IApplication, winrt::Microsoft::UI::Xaml::IApplication2, winrt::Microsoft::UI::Xaml::IApplication3>,
        impl::base<D, winrt::Microsoft::UI::Xaml::Application>,
        winrt::Microsoft::UI::Xaml::IApplicationOverridesT<D>
    {
        using base_type = App_base;
        using class_type = GlassPlayer::App;
        using implements_type = typename App_base::implements_type;
        using implements_type::implements_type;
        using composable_base = winrt::Microsoft::UI::Xaml::Application;
        hstring GetRuntimeClassName() const
        {
            return L"GlassPlayer.App";
        }
        App_base()
        {
            impl::call_factory<winrt::Microsoft::UI::Xaml::Application, winrt::Microsoft::UI::Xaml::IApplicationFactory>([&](winrt::Microsoft::UI::Xaml::IApplicationFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
}
namespace winrt::GlassPlayer::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES AppT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = GlassPlayer::App;

        hstring GetRuntimeClassName() const
        {
            return L"GlassPlayer.App";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_APP_XAML_G_H) || __has_include("App.xaml.g.h")

#include "App.xaml.g.h"

#else

namespace winrt::GlassPlayer::implementation
{
    template <typename D, typename... I>
    using AppT = App_base<D, I...>;
}

#endif
