// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#include "winrt/base.h"
#include "App.h"
#include "MainWindow.h"
#include "RcloneBrowser.h"
#include "SettingsWindow.h"
#include "WelcomeWindow.h"
#include "XamlMetaDataProvider.h"

bool __stdcall winrt_can_unload_now() noexcept
{
    if (winrt::get_module_lock())
    {
        return false;
    }

    winrt::clear_factory_cache();
    return true;
}

void* __stdcall winrt_get_activation_factory([[maybe_unused]] std::wstring_view const& name)
{
    auto requal = [](std::wstring_view const& left, std::wstring_view const& right) noexcept
    {
        return std::equal(left.rbegin(), left.rend(), right.rbegin(), right.rend());
    };

    if (requal(name, L"GlassPlayer.App"))
    {
        return winrt::detach_abi(winrt::make<winrt::GlassPlayer::factory_implementation::App>());
    }

    if (requal(name, L"GlassPlayer.MainWindow"))
    {
        return winrt::detach_abi(winrt::make<winrt::GlassPlayer::factory_implementation::MainWindow>());
    }

    if (requal(name, L"GlassPlayer.RcloneBrowser"))
    {
        return winrt::detach_abi(winrt::make<winrt::GlassPlayer::factory_implementation::RcloneBrowser>());
    }

    if (requal(name, L"GlassPlayer.SettingsWindow"))
    {
        return winrt::detach_abi(winrt::make<winrt::GlassPlayer::factory_implementation::SettingsWindow>());
    }

    if (requal(name, L"GlassPlayer.WelcomeWindow"))
    {
        return winrt::detach_abi(winrt::make<winrt::GlassPlayer::factory_implementation::WelcomeWindow>());
    }

    if (requal(name, L"GlassPlayer.XamlMetaDataProvider"))
    {
        return winrt::detach_abi(winrt::make<winrt::GlassPlayer::factory_implementation::XamlMetaDataProvider>());
    }

    return nullptr;
}

int32_t __stdcall WINRT_CanUnloadNow() noexcept
{
#ifdef _WRL_MODULE_H_
    if (!::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().Terminate())
    {
        return 1;
    }
#endif

    return winrt_can_unload_now() ? 0 : 1;
}

int32_t __stdcall WINRT_GetActivationFactory(void* classId, void** factory) noexcept try
{
    std::wstring_view const name{ *reinterpret_cast<winrt::hstring*>(&classId) };
    *factory = winrt_get_activation_factory(name);

    if (*factory)
    {
        return 0;
    }

#ifdef _WRL_MODULE_H_
    return ::Microsoft::WRL::Module<::Microsoft::WRL::InProc>::GetModule().GetActivationFactory(static_cast<HSTRING>(classId), reinterpret_cast<::IActivationFactory**>(factory));
#else
    return winrt::hresult_class_not_available(name).to_abi();
#endif
}
catch (...) { return winrt::to_hresult(); }
