// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#include "winrt/GlassPlayer.h"
#include "winrt/Microsoft.UI.Xaml.h"
namespace winrt::GlassPlayer::implementation
{
    template <typename D, typename... I>
    struct WINRT_IMPL_EMPTY_BASES RcloneBrowser_base : implements<D, GlassPlayer::RcloneBrowser, composing, I...>,
        impl::require<D, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>,
        impl::base<D, winrt::Microsoft::UI::Xaml::Window>
    {
        using base_type = RcloneBrowser_base;
        using class_type = GlassPlayer::RcloneBrowser;
        using implements_type = typename RcloneBrowser_base::implements_type;
        using implements_type::implements_type;
        using composable_base = winrt::Microsoft::UI::Xaml::Window;
        hstring GetRuntimeClassName() const
        {
            return L"GlassPlayer.RcloneBrowser";
        }
        RcloneBrowser_base()
        {
            impl::call_factory<winrt::Microsoft::UI::Xaml::Window, winrt::Microsoft::UI::Xaml::IWindowFactory>([&](winrt::Microsoft::UI::Xaml::IWindowFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
}
namespace winrt::GlassPlayer::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct WINRT_IMPL_EMPTY_BASES RcloneBrowserT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = GlassPlayer::RcloneBrowser;

        hstring GetRuntimeClassName() const
        {
            return L"GlassPlayer.RcloneBrowser";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_RCLONEBROWSER_XAML_G_H) || __has_include("RcloneBrowser.xaml.g.h")

#include "RcloneBrowser.xaml.g.h"

#else

namespace winrt::GlassPlayer::implementation
{
    template <typename D, typename... I>
    using RcloneBrowserT = RcloneBrowser_base<D, I...>;
}

#endif
