#!/usr/bin/env swift

// ---------------------------------------------------------------------------
// ExtractWeights.swift - Extract CNN weights from Anime4K Metal shaders
//
// Reads each .metal file in GlassPlayer/MetalShaders/, finds all kernel
// functions, extracts float4x4(...) weight literals in order, and emits
// GlassPlayer/Sources/Anime4KWeights.swift with static let arrays.
// ---------------------------------------------------------------------------

import Foundation

let metalShadersDir = "GlassPlayer/MetalShaders"
let outputFile = "GlassPlayer/Sources/Anime4KWeights.swift"

// Regex to match float4x4(...) weight literals
// Matches: float4x4(num, num, num, num, num, num, num, num, num, num, num, num, num, num, num, num)
let float4x4Regex = try! NSRegularExpression(
    pattern: "float4x4\\(([^)]+)\\)",
    options: []
)

// Regex to match kernel function names
let kernelFunctionRegex = try! NSRegularExpression(
    pattern: "kernel\\s+void\\s+(\\w+)",
    options: []
)

// Map shader file to kernel functions
struct KernelWeights {
    let kernelName: String
    let weights: [[Float]]  // Each [Float] is 16 elements (flattened float4x4)
}

struct ShaderFile {
    let filename: String
    let kernels: [KernelWeights]
}

func extractFloats(from string: String) -> [Float]? {
    let components = string.components(separatedBy: CharacterSet(charactersIn: " ,"))
    var floats: [Float] = []
    for component in components {
        let trimmed = component.trimmingCharacters(in: .whitespaces)
        if trimmed.isEmpty { continue }
        if let float = Float(trimmed) {
            floats.append(float)
        } else {
            // Handle scientific notation (e.g., "8.8084314e-05")
            if let float = Float(trimmed.replacingOccurrences(of: "e-", with: "e-")) {
                floats.append(float)
            }
        }
    }
    // float4x4 has exactly 16 elements
    return floats.count == 16 ? floats : nil
}

func processMetalFile(_ filepath: String) -> [KernelWeights]? {
    guard let content = try? String(contentsOfFile: filepath, encoding: .utf8) else {
        print("  Failed to read: \(filepath)")
        return nil
    }

    var kernels: [KernelWeights] = []

    // Find all kernel function declarations
    let kernelMatches = kernelFunctionRegex.matches(
        in: content,
        range: NSRange(content.startIndex..., in: content)
    )

    for kernelMatch in kernelMatches {
        guard let kernelNameRange = Range(kernelMatch.range(at: 1), in: content) else { continue }
        let kernelName = String(content[kernelNameRange])

        // Find the kernel function body
        let kernelStart = kernelMatch.range.location
        let remainingContent = String(content.dropFirst(kernelStart))

        // Find all float4x4(...) in this kernel's scope
        // We need to find the function body and extract weights from it
        var weights: [[Float]] = []

        let float4x4Matches = float4x4Regex.matches(
            in: remainingContent,
            range: NSRange(remainingContent.startIndex..., in: remainingContent)
        )

        for match in float4x4Matches {
            guard let argsRange = Range(match.range(at: 1), in: remainingContent) else { continue }
            let argsString = String(remainingContent[argsRange])
            if let floats = extractFloats(from: argsString) {
                weights.append(floats)
            }
        }

        if !weights.isEmpty {
            kernels.append(KernelWeights(kernelName: kernelName, weights: weights))
            print("  Found kernel: \(kernelName) with \(weights.count) weight matrices")
        }
    }

    return kernels.isEmpty ? nil : kernels
}

func swiftFloatLiteral(_ floats: [Float]) -> String {
    let formatted = floats.map { f -> String in
        if f == 0.0 { return "0.0" }
        if f == 1.0 { return "1.0" }
        if f == -1.0 { return "-1.0" }
        // Use sufficient precision for ML weights
        return String(format: "%.8f", f)
    }
    return "[\(formatted.joined(separator: ", "))]"
}

func generateSwiftFile(_ shaders: [ShaderFile]) -> String {
    var output = """
// ---------------------------------------------------------------------------
// Anime4KWeights.swift - CNN weights extracted from Metal shaders
//
// Auto-generated by Scripts/ExtractWeights.swift
// DO NOT EDIT MANUALLY
//
// These weights are used by MPSCNNConvolution for Neural Engine acceleration.
// Each weight array corresponds to a convolution kernel in the Anime4K pipeline.
// ---------------------------------------------------------------------------

import Foundation

/// CNN weights for Anime4K Metal pipeline
/// Each weight array contains Float values in the order expected by MPSCNNConvolution
/// Format: [outputChannel][inputChannel][kernelHeight][kernelWidth] flattened
struct Anime4KWeights {

"""

    for shader in shaders {
        output += """
    // MARK: - \(shader.filename)

"""
        for kernel in shader.kernels {
            // Sanitize kernel name for Swift identifier
            let swiftName = kernel.kernelName
                .replacingOccurrences(of: "-", with: "_")
                .replacingOccurrences(of: ".", with: "_")

            output += "    /// Weights for kernel: \(kernel.kernelName)\n"
            output += "    static let weights_\(swiftName): [[Float]] = [\n"

            for (i, weightMatrix) in kernel.weights.enumerated() {
                output += "        \(swiftFloatLiteral(weightMatrix))"
                if i < kernel.weights.count - 1 {
                    output += ","
                }
                output += "\n"
            }

            output += "    ]\n\n"
        }
    }

    output += "}\n"
    return output
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

print("Extracting CNN weights from Metal shaders...")
print("Input directory: \(metalShadersDir)")
print("Output file: \(outputFile)")
print("")

var allShaders: [ShaderFile] = []

// Get all .metal files
guard let enumerator = FileManager.default.enumerator(
    at: URL(fileURLWithPath: metalShadersDir),
    includingPropertiesForKeys: nil
) else {
    fatalError("Failed to enumerate \(metalShadersDir)")
}

for case let fileURL as URL in enumerator {
    guard fileURL.pathExtension == "metal" else { continue }
    let filepath = fileURL.path
    print("Processing: \(filepath)")

    if let kernels = processMetalFile(filepath) {
        let filename = fileURL.deletingPathExtension().lastPathComponent
        allShaders.append(ShaderFile(filename: filename, kernels: kernels))
    }
    print("")
}

if allShaders.isEmpty {
    fatalError("No weights extracted - check shader files")
}

// Generate Swift file
print("Generating \(outputFile)...")
let swiftContent = generateSwiftFile(allShaders)

do {
    try swiftContent.write(toFile: outputFile, atomically: true, encoding: .utf8)
    print("Successfully generated \(outputFile)")
    print("Total shaders: \(allShaders.count)")
    let totalKernels = allShaders.reduce(0) { $0 + $1.kernels.count }
    print("Total kernels: \(totalKernels)")
} catch {
    fatalError("Failed to write output file: \(error)")
}
