
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Input.h>)
#include <winrt/Microsoft.UI.Xaml.Input.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif
#if __has_include(<winrt/Windows.Foundation.h>)
#include <winrt/Windows.Foundation.h>
#endif


namespace winrt::GlassPlayer::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainWindowT : public ::winrt::GlassPlayer::implementation::MainWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainWindowT::base_type;
        using base_type::base_type;
        using class_type = typename MainWindowT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::Grid Root()
        {
            return _Root;
        }
        void Root(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _Root = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::SwapChainPanel VideoPanel()
        {
            return _VideoPanel;
        }
        void VideoPanel(::winrt::Microsoft::UI::Xaml::Controls::SwapChainPanel value)
        {
            _VideoPanel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border TopBar()
        {
            return _TopBar;
        }
        void TopBar(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _TopBar = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border BottomBar()
        {
            return _BottomBar;
        }
        void BottomBar(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _BottomBar = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border BrightnessBar()
        {
            return _BrightnessBar;
        }
        void BrightnessBar(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _BrightnessBar = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border VolumeBar()
        {
            return _VolumeBar;
        }
        void VolumeBar(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _VolumeBar = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Image VolumeBarIcon()
        {
            return _VolumeBarIcon;
        }
        void VolumeBarIcon(::winrt::Microsoft::UI::Xaml::Controls::Image value)
        {
            _VolumeBarIcon = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Slider VolumeHoverSlider()
        {
            return _VolumeHoverSlider;
        }
        void VolumeHoverSlider(::winrt::Microsoft::UI::Xaml::Controls::Slider value)
        {
            _VolumeHoverSlider = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Slider BrightnessSlider()
        {
            return _BrightnessSlider;
        }
        void BrightnessSlider(::winrt::Microsoft::UI::Xaml::Controls::Slider value)
        {
            _BrightnessSlider = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Canvas BottomCanvas()
        {
            return _BottomCanvas;
        }
        void BottomCanvas(::winrt::Microsoft::UI::Xaml::Controls::Canvas value)
        {
            _BottomCanvas = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock CurrentTimeLabel()
        {
            return _CurrentTimeLabel;
        }
        void CurrentTimeLabel(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _CurrentTimeLabel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Slider SeekSlider()
        {
            return _SeekSlider;
        }
        void SeekSlider(::winrt::Microsoft::UI::Xaml::Controls::Slider value)
        {
            _SeekSlider = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock RemainingTimeLabel()
        {
            return _RemainingTimeLabel;
        }
        void RemainingTimeLabel(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _RemainingTimeLabel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button SubtitleBtn()
        {
            return _SubtitleBtn;
        }
        void SubtitleBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _SubtitleBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button AudioBtn()
        {
            return _AudioBtn;
        }
        void AudioBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _AudioBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button ShaderBtn()
        {
            return _ShaderBtn;
        }
        void ShaderBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _ShaderBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button PrevBtn()
        {
            return _PrevBtn;
        }
        void PrevBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _PrevBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button RewindBtn()
        {
            return _RewindBtn;
        }
        void RewindBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _RewindBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button PlayPauseBtn()
        {
            return _PlayPauseBtn;
        }
        void PlayPauseBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _PlayPauseBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button ForwardBtn()
        {
            return _ForwardBtn;
        }
        void ForwardBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _ForwardBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button NextBtn()
        {
            return _NextBtn;
        }
        void NextBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _NextBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button VolumeBtn()
        {
            return _VolumeBtn;
        }
        void VolumeBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _VolumeBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Slider VolumeSlider()
        {
            return _VolumeSlider;
        }
        void VolumeSlider(::winrt::Microsoft::UI::Xaml::Controls::Slider value)
        {
            _VolumeSlider = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button SpeedBtn()
        {
            return _SpeedBtn;
        }
        void SpeedBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _SpeedBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button AspectBtn()
        {
            return _AspectBtn;
        }
        void AspectBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _AspectBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button FullscreenBtn()
        {
            return _FullscreenBtn;
        }
        void FullscreenBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _FullscreenBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Image FullscreenIcon()
        {
            return _FullscreenIcon;
        }
        void FullscreenIcon(::winrt::Microsoft::UI::Xaml::Controls::Image value)
        {
            _FullscreenIcon = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Image VolumeIcon()
        {
            return _VolumeIcon;
        }
        void VolumeIcon(::winrt::Microsoft::UI::Xaml::Controls::Image value)
        {
            _VolumeIcon = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Image PlayPauseIcon()
        {
            return _PlayPauseIcon;
        }
        void PlayPauseIcon(::winrt::Microsoft::UI::Xaml::Controls::Image value)
        {
            _PlayPauseIcon = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox UrlEdit()
        {
            return _UrlEdit;
        }
        void UrlEdit(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _UrlEdit = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button UrlBtn()
        {
            return _UrlBtn;
        }
        void UrlBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _UrlBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button OpenBtn()
        {
            return _OpenBtn;
        }
        void OpenBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _OpenBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button RemoteBtn()
        {
            return _RemoteBtn;
        }
        void RemoteBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _RemoteBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button SettingsBtn()
        {
            return _SettingsBtn;
        }
        void SettingsBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _SettingsBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock TitleLabel()
        {
            return _TitleLabel;
        }
        void TitleLabel(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _TitleLabel = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Border ResolutionBadge()
        {
            return _ResolutionBadge;
        }
        void ResolutionBadge(::winrt::Microsoft::UI::Xaml::Controls::Border value)
        {
            _ResolutionBadge = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock ResolutionText()
        {
            return _ResolutionText;
        }
        void ResolutionText(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _ResolutionText = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct MainWindow_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::Grid _Root{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::SwapChainPanel _VideoPanel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _TopBar{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _BottomBar{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _BrightnessBar{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _VolumeBar{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Image _VolumeBarIcon{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Slider _VolumeHoverSlider{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Slider _BrightnessSlider{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Canvas _BottomCanvas{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _CurrentTimeLabel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Slider _SeekSlider{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _RemainingTimeLabel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _SubtitleBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _AudioBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _ShaderBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _PrevBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _RewindBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _PlayPauseBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _ForwardBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _NextBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _VolumeBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Slider _VolumeSlider{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _SpeedBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _AspectBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _FullscreenBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Image _FullscreenIcon{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Image _VolumeIcon{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Image _PlayPauseIcon{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _UrlEdit{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _UrlBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _OpenBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _RemoteBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _SettingsBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _TitleLabel{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Border _ResolutionBadge{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _ResolutionText{nullptr};
    };
}

