
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Input.h>)
#include <winrt/Microsoft.UI.Xaml.Input.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::GlassPlayer::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct RcloneBrowserT : public ::winrt::GlassPlayer::implementation::RcloneBrowser_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename RcloneBrowserT::base_type;
        using base_type::base_type;
        using class_type = typename RcloneBrowserT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::ListView DirectoryList()
        {
            return _DirectoryList;
        }
        void DirectoryList(::winrt::Microsoft::UI::Xaml::Controls::ListView value)
        {
            _DirectoryList = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button BackBtn()
        {
            return _BackBtn;
        }
        void BackBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _BackBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button UpBtn()
        {
            return _UpBtn;
        }
        void UpBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _UpBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button RefreshBtn()
        {
            return _RefreshBtn;
        }
        void RefreshBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _RefreshBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox UrlField()
        {
            return _UrlField;
        }
        void UrlField(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _UrlField = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button ConnectBtn()
        {
            return _ConnectBtn;
        }
        void ConnectBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _ConnectBtn = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct RcloneBrowser_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::ListView _DirectoryList{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _BackBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _UpBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _RefreshBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _UrlField{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _ConnectBtn{nullptr};
    };
}

