
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::GlassPlayer::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct SettingsWindowT : public ::winrt::GlassPlayer::implementation::SettingsWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename SettingsWindowT::base_type;
        using base_type::base_type;
        using class_type = typename SettingsWindowT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::ListView SidebarList()
        {
            return _SidebarList;
        }
        void SidebarList(::winrt::Microsoft::UI::Xaml::Controls::ListView value)
        {
            _SidebarList = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Grid ContentStack()
        {
            return _ContentStack;
        }
        void ContentStack(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _ContentStack = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer GeneralPage()
        {
            return _GeneralPage;
        }
        void GeneralPage(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _GeneralPage = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer VideoPage()
        {
            return _VideoPage;
        }
        void VideoPage(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _VideoPage = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer AudioPage()
        {
            return _AudioPage;
        }
        void AudioPage(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _AudioPage = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer SubtitlesPage()
        {
            return _SubtitlesPage;
        }
        void SubtitlesPage(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _SubtitlesPage = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer NetworkPage()
        {
            return _NetworkPage;
        }
        void NetworkPage(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _NetworkPage = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer ScalingPage()
        {
            return _ScalingPage;
        }
        void ScalingPage(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _ScalingPage = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer ColorPage()
        {
            return _ColorPage;
        }
        void ColorPage(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _ColorPage = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer Anime4KPage()
        {
            return _Anime4KPage;
        }
        void Anime4KPage(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _Anime4KPage = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer ShortcutsPage()
        {
            return _ShortcutsPage;
        }
        void ShortcutsPage(::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer value)
        {
            _ShortcutsPage = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox Anime4KPresetCombo()
        {
            return _Anime4KPresetCombo;
        }
        void Anime4KPresetCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _Anime4KPresetCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox TargetColorspaceCheck()
        {
            return _TargetColorspaceCheck;
        }
        void TargetColorspaceCheck(::winrt::Microsoft::UI::Xaml::Controls::CheckBox value)
        {
            _TargetColorspaceCheck = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox HdrPeakCheck()
        {
            return _HdrPeakCheck;
        }
        void HdrPeakCheck(::winrt::Microsoft::UI::Xaml::Controls::CheckBox value)
        {
            _HdrPeakCheck = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox ToneMappingCombo()
        {
            return _ToneMappingCombo;
        }
        void ToneMappingCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _ToneMappingCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox ScaleCombo()
        {
            return _ScaleCombo;
        }
        void ScaleCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _ScaleCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox CscaleCombo()
        {
            return _CscaleCombo;
        }
        void CscaleCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _CscaleCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox CacheSizeText()
        {
            return _CacheSizeText;
        }
        void CacheSizeText(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _CacheSizeText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox UserAgentText()
        {
            return _UserAgentText;
        }
        void UserAgentText(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _UserAgentText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox TimeoutText()
        {
            return _TimeoutText;
        }
        void TimeoutText(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _TimeoutText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox SubFontText()
        {
            return _SubFontText;
        }
        void SubFontText(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _SubFontText = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Slider SubSizeSlider()
        {
            return _SubSizeSlider;
        }
        void SubSizeSlider(::winrt::Microsoft::UI::Xaml::Controls::Slider value)
        {
            _SubSizeSlider = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox SubBoldCheck()
        {
            return _SubBoldCheck;
        }
        void SubBoldCheck(::winrt::Microsoft::UI::Xaml::Controls::CheckBox value)
        {
            _SubBoldCheck = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox AudioDriverCombo()
        {
            return _AudioDriverCombo;
        }
        void AudioDriverCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _AudioDriverCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox ChannelsCombo()
        {
            return _ChannelsCombo;
        }
        void ChannelsCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _ChannelsCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox SpdifCheck()
        {
            return _SpdifCheck;
        }
        void SpdifCheck(::winrt::Microsoft::UI::Xaml::Controls::CheckBox value)
        {
            _SpdifCheck = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox HwdecCombo()
        {
            return _HwdecCombo;
        }
        void HwdecCombo(::winrt::Microsoft::UI::Xaml::Controls::ComboBox value)
        {
            _HwdecCombo = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox VsyncCheck()
        {
            return _VsyncCheck;
        }
        void VsyncCheck(::winrt::Microsoft::UI::Xaml::Controls::CheckBox value)
        {
            _VsyncCheck = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox InterpolationCheck()
        {
            return _InterpolationCheck;
        }
        void InterpolationCheck(::winrt::Microsoft::UI::Xaml::Controls::CheckBox value)
        {
            _InterpolationCheck = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox FullscreenCheck()
        {
            return _FullscreenCheck;
        }
        void FullscreenCheck(::winrt::Microsoft::UI::Xaml::Controls::CheckBox value)
        {
            _FullscreenCheck = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox AutoResumeCheck()
        {
            return _AutoResumeCheck;
        }
        void AutoResumeCheck(::winrt::Microsoft::UI::Xaml::Controls::CheckBox value)
        {
            _AutoResumeCheck = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox PlayDropCheck()
        {
            return _PlayDropCheck;
        }
        void PlayDropCheck(::winrt::Microsoft::UI::Xaml::Controls::CheckBox value)
        {
            _PlayDropCheck = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox UpdatesCheck()
        {
            return _UpdatesCheck;
        }
        void UpdatesCheck(::winrt::Microsoft::UI::Xaml::Controls::CheckBox value)
        {
            _UpdatesCheck = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct SettingsWindow_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::ListView _SidebarList{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Grid _ContentStack{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _GeneralPage{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _VideoPage{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _AudioPage{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _SubtitlesPage{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _NetworkPage{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _ScalingPage{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _ColorPage{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _Anime4KPage{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ScrollViewer _ShortcutsPage{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _Anime4KPresetCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox _TargetColorspaceCheck{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox _HdrPeakCheck{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _ToneMappingCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _ScaleCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _CscaleCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _CacheSizeText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _UserAgentText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _TimeoutText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _SubFontText{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Slider _SubSizeSlider{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox _SubBoldCheck{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _AudioDriverCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _ChannelsCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox _SpdifCheck{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::ComboBox _HwdecCombo{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox _VsyncCheck{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox _InterpolationCheck{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox _FullscreenCheck{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox _AutoResumeCheck{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox _PlayDropCheck{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::CheckBox _UpdatesCheck{nullptr};
    };
}

