
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include <unknwn.h>

// Undefine GetCurrentTime macro to prevent
// conflict with Storyboard::GetCurrentTime
#undef GetCurrentTime

#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#include <winrt/Microsoft.UI.Xaml.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Controls.Primitives.h>)
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#endif
#if __has_include(<winrt/Microsoft.UI.Xaml.Markup.h>)
#include <winrt/Microsoft.UI.Xaml.Markup.h>
#endif


namespace winrt::GlassPlayer::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct WelcomeWindowT : public ::winrt::GlassPlayer::implementation::WelcomeWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename WelcomeWindowT::base_type;
        using base_type::base_type;
        using class_type = typename WelcomeWindowT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::Grid RootGrid()
        {
            return _RootGrid;
        }
        void RootGrid(::winrt::Microsoft::UI::Xaml::Controls::Grid value)
        {
            _RootGrid = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button OpenFileBtn()
        {
            return _OpenFileBtn;
        }
        void OpenFileBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _OpenFileBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button RemoteBtn()
        {
            return _RemoteBtn;
        }
        void RemoteBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _RemoteBtn = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::Button CloseBtn()
        {
            return _CloseBtn;
        }
        void CloseBtn(::winrt::Microsoft::UI::Xaml::Controls::Button value)
        {
            _CloseBtn = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct WelcomeWindow_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::Grid _RootGrid{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _OpenFileBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _RemoteBtn{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::Button _CloseBtn{nullptr};
    };
}

